# FILE     Makefile
# PACKAGE  PrimitiveStats
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for test programs of the "PrimitiveStats" package.
#
# COPYRIGHT (C) 1997 Basis Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ..; pwd)


#I
include ../etc/Basis/MakeDef


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
