# FILE     Makefile
# PACKAGE  MarioGraph
# AUTHOR   Mario Drobics
#
# CONTENT
#   Makefile for example programs of the "MarioGraph" package.
#
# COPYRIGHT (C)  1997 CoreObjects Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/CoreObjects/MakeDef

LDLIBS+=\
  -lMarioGraph


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
