# FILE     Makefile
# PACKAGE  Fuzzy
# AUTHOR   Harald Wahl
#
# CONTENT
#   Makefile for example programs of the "Fuzzy" package.
#
# COPYRIGHT (C)  1997 CoreObjects Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/CoreObjects/MakeDef

LDLIBS+=\
  -lFuzzy


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
